services:
  # データベースサービス
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Railsアプリケーションサービス
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # DB作成とマイグレーションはすでに正常に存在する場合は、スキップされる
    # docker compose upするたびに、railsサーバーを自動で立ち上げる
    command: >
      sh -c "bundle exec rails db:create db:migrate &&
             bundle exec rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  bundle_data: