default: &default
  adapter: postgresql
  encoding: unicode
  host: db  # ← ここがポイント！
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  # 本番環境ではNeonのデータベースURLを読み込めるようにする
  url: <%= ENV['DATABASE_URL'] %>